import type { NextPage } from 'next'
import Image from 'next/image'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Delsco Enterprises</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
        <div className="flex justify-center">
          <div className="text-center">
            <Image
              src="/logo.png"
              alt="Delsco Enterprises"
              width={200}
              height={200}
            />
            <div className="mt-5">
              <h1 className="text-4xl tracking-tight font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
                <span className="block text-red-900 xl:inline">Delsco Enterprises</span>
              </h1>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}

export default Home
